### ISSUE TITLE
Colored sidebar items prefix 7 is used for all the prefixes after

### ISSUE THREAD

**Issue by darkermango** [Elevict/Elevict-Snippets#1]
the color `--prefix-07` is used for the lines after 8, 9, 10, 11 etc. I think it's an error from repeating copy/paste and a drop of attention.
![image](https://github.com/user-attachments/assets/31561a9c-4543-40a3-add7-5c5d17497937)

**Comment by Elevict** [comment]
Should be fixed now. Try it out.
