### ISSUE TITLE
Adding New Prefix Breaks Style Settings

### ISSUE THREAD

**Issue by lilybugg13** [Elevict/Elevict-Snippets#3]
Hey, I'm a dunce when it comes to code and was originally using Vauxhall's colored sidebar snippet. Got this one because I changed themes and using the Style Settings was far simpler to change the colors. However, I wanted to add a new prefix (99 for Meta) and I tried copying and pasting one of the other prefixes and just changing the number to 99 and now the Style Settings is coming up with this error. 
![image](https://github.com/user-attachments/assets/e5fdb30f-569c-49b8-a9ac-ccb8af9c2977)

Here's what I copied and changed 

`   id: prefix-12
    title: Prefix 12
    type: variable-themed-color
    format: hex
    default-light: '#'
    default-dark: '#'`

to

`   id: prefix-99
    title: Prefix 99
    type: variable-themed-color
    format: hex
    default-light: '#'
    default-dark: '#'`

Literally just changing the number. I don't know if I messed up elsewhere there and forgot to change something, but the rest of the prefix settings are the same. This is all underneath the settings comment at the top of the code. 

Then I copied 
`.nav-folder-title[data-path^="12"],
.nav-file-title[data-path^="12"] { --prefix-color: var(--prefix-12); }`

to 

`.nav-folder-title[data-path^="99"],
.nav-file-title[data-path^="99"] { --prefix-color: var(--prefix-99); }`

And after scanning the rest of the code, it didn't look like there was something else I needed to add in order to add a new prefix. I don't know if I'm doing something wrong or if I can't add a new prefix like this. Once again, I'm not very good at code and I apologize if this is the simplest solution ever and I can't figure it out.

**Comment by Elevict** [comment]
You did everything correctly, you just forgot the most important part in adding/changing the `--prefix-99` variable in body. So you would want to copy `--prefix-12: #FF9900;` and turn it into `--prefix-99: red;` or whatever default color it is you want. If you look at your error, notice how its unable to find --prefix-99 because you haven't defined it yet. You can check here to see and learn how variables work: https://www.w3schools.com/css/css3_variables.asp

**Comment by lilybugg13** [comment]
I actually did do that, totally forgot to add that I had done that.

`--prefix-99: #515768;`

It actually works because it does change the folder that has the 99 as the gray color, but the style settings is still messed up and so I can't go in and change the font or colors via the plugin. 

![image](https://github.com/user-attachments/assets/028e1ecb-ae79-4fb1-a470-a29bdb870c10)

**Comment by Elevict** [comment]
Please check your style settings comments and see that you do not have a copy of `id: prefix-99`. This should be before line 114 in your css file, and you can check it quickly by doing `ctrl+f`. If you have a copy of the id, remove it or change it into something else.

**Comment by lilybugg13** [comment]
![image](https://github.com/user-attachments/assets/431e6224-8127-4721-867a-e254265786ee)

This is the only place where I have the id for prefix-99. Ctrl+f showed only this.

**Comment by Elevict** [comment]
You forgot a `-` in line 125.

**Comment by lilybugg13** [comment]
.........

I feel like I wasted so much of your time for the simplest of fixes oh my god this is why I _hate_ coding. It's always something like this. Anyways, thank you very much for your help and I apologize. That was the issue and now all is well with the word x'D
